services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}-webapp:latest
    ports:
      - "80:3000"
    env_file:
      - ./webapp/.env.docker
    volumes:
      - feedback_data:/data

volumes:
  feedback_data:
